import type { Metadata } from "next";

import "./globals.css";
import { inter } from "./font";

export const metadata: Metadata = {
  title: "landing page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${inter.className} antialiased`}>
      <body>{children}</body>
    </html>
  );
}
